package com.project.backend.common.response;

public enum Message {

    OK,
    CREATED,
    BAD_REQUEST,
    PASSWORD_NOT_MATCHES,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,


    POST_NOT_FOUND,
    NOT_WRITER_OF_THIS_POST,


    METHOD_NOT_ALLOWED,
    HTTP_MEDIA_TYPE_NOT_ACCEPTABLE,
    INVALID_DATA_ACCESS_API_USAGE,
    INTERNAL_SERVER_ERROR


}
