spring:
  datasource:
#    url: jdbc:mysql://${memodot_mysql_host:localhost}:${memodot_mysql_port:3306}/memodot
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${memodot_mysql_username}
#    password: ${memodot_mysql_password}

    url: jdbc:mysql://localhost:3306/memodot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: localhost
    password: localhost
#    url: jdbc:mysql://localhost:3306/memodot
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

